######################################################################
# Automatically generated by qmake (2.01a) lun. avr. 4 16:42:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += testlib

# Input
HEADERS += RessourceTests.hpp

SOURCES += ../../src/tools/Log.cpp
