######################################################################
# Automatically generated by qmake (2.01a) lun. avr. 4 16:42:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += testlib

LIBS += -ltinyxml

# Input
HEADERS += MapTest.hpp

SOURCES += ../../src/tools/Log.cpp \
           ../../src/Map.cpp
